### ISSUE TITLE
No way to disable C part of backtrace-sys

### ISSUE THREAD

**Issue by kornelski** [alexcrichton/backtrace-rs#162]
I would like to run `cargo check --target=<other platform>` to check if my conditional Rust code is valid for the given platform. 

I don't have a working C cross-compiler for that platform, but backtrace-sys requires C compiler at build-time on all platforms it has C for.

It would be helpful if I could skip backtrace-sys' C compilation part for my `cargo check` use-cases, e.g. by setting an env variable, e.g.

```sh
BACKTRACE_ENABLED=0 cargo check
```

**Comment by alexcrichton** [comment]
I'm going to close this because I think this is a more general problem than just this crate. If you want to skip C compilation then you can do something liek `CC=true AR=true cargo check`, but otherwise this is unfortunately just a bug larger than backtrace-sys itself but rather applicable to crates like `cc` and the entirety of Cargo.
