### ISSUE TITLE
Lazy backtrace

### ISSUE THREAD

**Issue by Yamakaky** [alexcrichton/backtrace-rs#30]
Do you think it would be feasible to add some kind of `LazyBacktrace`? Instead of calling [trace then resolve](https://github.com/alexcrichton/backtrace-rs/blob/master/src/capture.rs#L77-L98), it would only call trace, then have a `fn resolve() -> Backtrace`. Alternatively, it could be an enum with `Backtrace` and `Vec<Frame::ip>` as variants.

I came on this idea by thinking about https://github.com/brson/error-chain/issues/129#issuecomment-280523181.

**Comment by alexcrichton** [comment]
Seems plausible!

**Comment by alexcrichton** [comment]
Seems fine

**Comment by Yamakaky** [comment]
Yeah, it may be worth to add it. With https://play.rust-lang.org/?gist=6557542b1c00bce1c6528b7daccee877&version=stable&backtrace=1, `c()` is three times faster that `b()`.

**Comment by golddranks** [comment]
https://github.com/brson/error-chain/issues/129#issuecomment-281946612 If @mitsuhiko is right that  CoreSymbolication is especially slow at the rendering phase (and I am understanding correctly that "Lazy" here means that it collects the required info but lazily resolves it when the actual backtrace is needed...), this could lead to tremendous speedups on Mac.

**Comment by Yamakaky** [comment]
https://github.com/alexcrichton/backtrace-rs/pull/32

**Comment by RalfJung** [comment]
I was just hit by this -- `Backtrace::new` takes multiple seconds the first time it is run, and later it is still extremely expensive. I was wondering why the program suddenly ran so slow, and the reason ended up being `Err` values that were created and then caught again, but already had their backtrace resolved.

I had to resort to <https://github.com/solson/miri/pull/283> to fix this. Unfortunately, this means we have to use the low-level APIs (`trace` and `resolve`), which are not particularly pleasant to work with. (Getting an iterator rather than having to specify a closure would make this much nicer ;)

**Comment by alexcrichton** [comment]
> Getting an iterator rather than having to specify a closure would make this much nicer

Agreed! This is unfortunately, however, not possible due to how some platform apis are implemented.
