### ISSUE TITLE
macOS Sierra Xcode 8.3 - Cross Compilation failed - Is `objcopy` not installed?

### ISSUE THREAD

**Issue by yageek** [alexcrichton/backtrace-rs#40]
I'm currently trying to cross-compile a library for android.

I'm using dustup with the last target:
```
Default host: x86_64-apple-darwin

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-apple-ios
aarch64-linux-android
arm-linux-androideabi
armv7-apple-ios
armv7-linux-androideabi
armv7s-apple-ios
i386-apple-ios
i686-linux-android
x86_64-apple-darwin
x86_64-apple-ios

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.16.0 (30cf806ef 2017-03-10)
```

I have installed correctly the standalone NDK toolchain and set them up inside `.cargo/config`:
```
[target.aarch64-linux-android]
ar = "~/dev/rust/arm64/bin/aarch64-linux-android-ar"
linker = "~/dev/rust/arm64/bin/aarch64-linux-android-gcc"

[target.armv7-linux-androideabi]
ar = "/NDK/arm/bin/arm-linux-androideabi-ar"
linker = "~/dev/rust/arm/bin/arm-linux-androideabi-gcc"

[target.i686-linux-android]
ar = "~/dev/rust/x86/bin/i686-linux-android-ar"
linker = "~/dev/rust/x86/bin/i686-linux-android-gcc"
```
When I trigger `cargo build --target=arm-linux-androideabi`, the compilation failed telling me:
```
 Is `objcopy` not installed?
```
The long and complete output can be found here: https://gist.github.com/yageek/6f828bfb496d50856797cb65a453b725

**NOTE**: I had to manually specify the `CC` environment variable before to reach this point:
```
export CC=$HOME/dev/rust/arm/bin/arm-linux-androideabi-clang
```

If I did not do it, I have this error:

```
error: failed to run custom build command for `backtrace-sys v0.1.10`
process didn't exit successfully: `/Users/yheinrich/dev/ios/message-protocol/capi/target/debug/build/backtrace-sys-0c4d13204b0e1510/build-script-build` (exit code: 101)
--- stdout
OPT_LEVEL = Some("0")
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-apple-darwin")
TARGET = Some("arm-linux-androideabi")
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-apple-darwin")
CC_arm-linux-androideabi = None
CC_arm_linux_androideabi = None
TARGET_CC = None
CC = None
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-apple-darwin")
CFLAGS_arm-linux-androideabi = None
CFLAGS_arm_linux_androideabi = None
TARGET_CFLAGS = None
CFLAGS = None
PROFILE = Some("debug")
running: "/Users/yheinrich/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.10/src/libbacktrace/configure" "--with-pic" "--disable-multilib" "--disable-shared" "--disable-host-shared" "--target=arm-linux-androideabi" "--host=x86_64-apple-darwin"
checking build system type... x86_64-apple-darwin16.5.0
checking host system type... x86_64-apple-darwin
checking target system type... arm-unknown-linux-androideabi
checking for x86_64-apple-darwin-gcc... arm-linux-androideabi-gcc
checking for C compiler default output file name...

--- stderr
configure: WARNING: If you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used.
configure: error: in `/Users/yheinrich/dev/ios/component-protocol/capi/target/arm-linux-androideabi/debug/build/backtrace-sys-c41044212322c9f2/out':
configure: error: C compiler cannot create executables
See `config.log' for more details.
thread 'main' panicked at 'failed with: exit code: 77', /Users/yheinrich/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.10/build.rs:134
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...
```

**Comment by daiheitan** [comment]
Same here @alexcrichton

**Comment by daiheitan** [comment]
Ok, I find a workaround (maybe). The reason is that you need to use linux's `objcopy`, which is ported via `binutils`. It should be installed when you are installing `crosstool-ng` in order to compile the toolchain (during `brew install crosstool-ng`)

However, `binutils` installs `objcopy` with a prefix `g`, which adds a `gobjcopy` binary to your `/usr/local/bin`

So you have to create a symbol link `ln -s /usr/local/bin/gobjcopy /usr/local/bin/objcopy`, and the problem would be gone.

BTW: I'm hitting objcopy's file format unrecognized error after this. Turns out it's because OSX's ar is different from the gnu version. You need to create another symbol link 

`ln -s /usr/local/bin/gar /usr/local/bin/ar`

and reload the session

**Comment by alexcrichton** [comment]
Thanks for the report! I think I just pushed a commit to fix this, but can you test it out to make sure it works?

**Comment by daiheitan** [comment]
Hey @alexcrichton I cannot test it because after the walkaround, I encounted another problem in `miniz-sys` claiming undefined reference to `mz_deflate` (and many other variables). Would there be a possibility that `miniz-sys` is also not supporting cross-compilation? If it's so, I could file a bug there. (I am targeting linux x86_64 from osx)

**Comment by yageek** [comment]
Does this also fix the fact the C compiler is not found ?

**Comment by alexcrichton** [comment]
@daiheitan perhaps? I'm not sure though ...

@yageek maybe? I didn't reproduce this locally so I'm not sure.

**Comment by daiheitan** [comment]
@alexcrichton 
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libbacktrace.a(atomic.o) has no symbols
ar: illegal pathname found in archive member: /
thread 'main' panicked at '

failed to execute command: No such file or directory (os error 2)
Is `objcopy` not installed?
```

**Comment by alexcrichton** [comment]
@daiheitan can you gist the full build logs to help debug?

(a way to reproduce locally would also be quite nice)

**Comment by daiheitan** [comment]
I'm cross-compiling on OSX sierra to CentOS, following [this](https://www.reddit.com/r/rust/comments/5741ue/crosscompilation_on_macos_for_linux/?st=j1bin4hj&sh=654e3f03). The reason why I was running into backtrace-sys issue is because I used `png` crate.

After several tries I gave up and used vagrant to build the linux binaries.

**Comment by alexcrichton** [comment]
@daiheitan what was the name of the compiler you were using? Was there an `objcopy` binary installed next to it?

**Comment by daiheitan** [comment]
Using crosstool-ng, and I believe the compiler is gcc. In macos, `objcopy` is installed as `gobjcopy`. As I said in the former comment, if I create a link of `gobjcopy` as `objcopy`, the problem is gone.

**Comment by alexcrichton** [comment]
@daiheitan oh ok, thanks for the info. If you'd like, updating the [build script logic](https://github.com/alexcrichton/backtrace-rs/blob/master/backtrace-sys/build.rs) when finding `objcopy` would be most welcome as a PR!
